exports.QuestionSchema="Question Schemas"
exports.QuizzResultSchema="quizz schemas"
exports.UserSchemas="User Schemas"
exports.ImgQuestions="Image Questions"
exports.BlockSchema="BlockSchema"
exports.AccessTokenSchema="accesstokenschemas"