exports.SIGNED_IN="Signed in"
exports.WRONG_PASSWORDS="Wrong password"
exports.NO_ACCOUNTS="No accounts"
exports.SIGN_UP_SUCCESSFULLY="Sign up successfully"
exports.CHANGE_PASS="Change passwords"
exports.USER_ACCESS="User"
exports.ADMIN_ACCESS="Admin"
exports.OFFLINE="Offline"
exports.ONLINE="Online"
exports.NO_DATA_RECEIVED="No data received"
exports.PHONE_EXIST="Phone Number Exists"
exports.HASHED_PASSWORDS="*********"
exports.SIGNED_OUT="Signed Out"

exports.GENDER_MALE="male"
exports.GENDER_FEMALE="female"
exports.GENDER_UNDEFINE="undefined"